### ISSUE TITLE
emoji icon is hiding some text

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/plugin-admin-notes#15]
The Emoji icon sits inside the text box and hides the last couple letters entered in the field. This is an issue when typing, because you can't see the cursor when you reach the end of the box.
![emoji-hides-text](https://cloud.githubusercontent.com/assets/367562/22217813/58c319b6-e159-11e6-9b20-dd06b7d3442c.gif)

**Comment by binarygary** [comment]
https://github.com/WebDevStudios/plugin-admin-notes/tree/issue/15
