### ISSUE TITLE
Replace turn on/off auto-updates link with icon

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/plugin-admin-notes#16]
Instead of using a text link, I thought it might be better to use an icon to indicate the status of the auto-updates. 

Let's try using this icon to represent auto-updates:
http://fontawesome.io/icon/refresh/

If auto-updates are currently OFF, the icon should appear in gray.
If auto-updates are currently ON, the icon should appear in Green.

Clicking the icon, no matter the state, would toggle the state.

**Comment by binarygary** [comment]
I am totally in over my head here 🤣 
To confirm...the font awesome css file should be included in the plugin assets?  (NOT loaded from a cdn).
