### ISSUE TITLE
Missing Activate/Deactivate & Settings Links

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/plugin-admin-notes#19]
Added version 0.1.0 to my site. Missing Activate / deactivate links. Settings Links are gone as well. 

![screen shot 2017-01-24 at 6 51 00 pm](https://cloud.githubusercontent.com/assets/1626591/22276075/1d5d8588-e266-11e6-8b3e-84a0ce57bb69.png)

**Comment by binarygary** [comment]
Huh...that's kind of a big thing for me to miss...

**Comment by binarygary** [comment]
I wasn't returning the $actions data from the called function.  I pushed a commit directly to master in this case.
https://github.com/WebDevStudios/plugin-admin-notes/commit/348e83eda54796c43ee20b98e90fb40987985378
