### ISSUE TITLE
plugin-notes is already in use on the WP.org repo

### ISSUE THREAD

**Issue by binarygary** [WebDevStudios/plugin-admin-notes#2]
I changed the plugin slug and was going to push.  When testing this update on local I found (to my surprise) there was an update available for it.

**Comment by vegasgeek** [comment]
Ha, I just saw the update notice as well. OK, we'll need to come up with a different name for it.

**Comment by vegasgeek** [comment]
@binarygary Let's change the name of the plugin to Plugin Admin Notes and that should solve our slug issue.
