### ISSUE TITLE
Plugin Update Message Reveals White Box

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/plugin-admin-notes#20]
I have three plugins giving me a update-message notice. To the far right, there is a white box appearing below the "Add A Note" link. Clicking on Add A Note Link, displays the notes text field, however, white box still appears.

![screen shot 2017-01-24 at 6 55 49 pm](https://cloud.githubusercontent.com/assets/1626591/22276203/e91d2052-e266-11e6-8260-ca071c57a1aa.png)

**Comment by binarygary** [comment]
What version of WP?
What browser?

Now that I asked those 2 questions...it's kinda clear to me that the div I'm adding in isn't 100% height.  
This might need some help from a FED to figure out.

**Comment by vegasgeek** [comment]
I'm not seeing that issue at all. Here's what I see:
![image](https://cloud.githubusercontent.com/assets/367562/22322644/4e956f16-e352-11e6-9546-1b2bc509a964.png)

**Comment by binarygary** [comment]
@KrashKartMedia I think we need more info to chase this down.

**Comment by binarygary** [comment]
This specifically shows on premium updates that are notifying of updates outside of .org.

**Comment by binarygary** [comment]
What appears to be happening is we are adding a new column and some premium plugins write a notice to colspan=3.

I pushed an update in https://github.com/WebDevStudios/plugin-admin-notes/commit/3f2aa9c9c23230808dcad04d4fa8838c1de15012 and https://github.com/WebDevStudios/plugin-admin-notes/commit/c968b9a4f8544d94f119b1418b93e6e96cbd828f that remove the key directly from $wp_filter.  As this is only related to the plugin page (column specifically) this should have no greater impact.
