### ISSUE TITLE
Missing Add A Note Link On Some Plugins

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/plugin-admin-notes#21]
Genesis Tabs, Google Analytics by Monster Insights, Gravity Forms + Custom Post Types, Gravity Forms CSS Ready Class Selector & Hashtag URL Placeholder.

**Above mentioned plugins are free .org plugins. They are missing "Add A Note" link etc.**  

_Gravity Forms & Gravity Styles are paid 3rd party plugins. Also missing notes here._

Out of 44 plugins on my site, 10 are missing "Add A Note."

![screen shot 2017-01-24 at 7 00 38 pm](https://cloud.githubusercontent.com/assets/1626591/22276299/862179f2-e267-11e6-9485-f88ebb02c967.png)

**Comment by binarygary** [comment]
This is with the latest pull correct?

I installed Hashtag URL Replacers to test with and it loads the comments for me, so it doesn't seem that it is related to the slug.  Something else is going on.  
https://www.dropbox.com/s/leti8avtgw3rrhq/Screenshot%202017-01-24%2022.12.46.png?dl=0

Do you have duplicates of those plugins in any meaningful way?
Are there any errors in the console.log?
Do you have any kind of plugin that manipulates the plugins in any way?

Any ideas what might cause this?

**Comment by binarygary** [comment]
Hey @KrashKartMedia I pushed a new update that logs data about each plugin.
Please create a file named pluginnotes.log in the plugin folder.  If this file exists it will log the arrays for each plugin.  Can you send me that file after it's populated?

Thanks!

**Comment by binarygary** [comment]
Whoops! I guess I should push the update...
I also changed the initial load on the forms.  

First pass I loaded the form with admin-ajax but that's a lot of ajax calls and I wonder if perhaps that was problematic in the form loading.

**Comment by vegasgeek** [comment]
This looks fixed to me.

**Comment by binarygary** [comment]
Verified with @KrashKartMedia on a call today...whee!!!
