### ISSUE TITLE
The lock icon seems to not work if it is the first item clicked

### ISSUE THREAD

**Issue by binarygary** [WebDevStudios/plugin-admin-notes#22]
If I click lock first, the admin-ajax request is not fired,
however if a note is added or auto updates are turned on the lock icons works as expected.

**Comment by binarygary** [comment]
This seems to be solved by reducing the number of admin-ajax calls (initially 1/plugin on page ready) by populating the form div from the start.
I'll leave this here for tracking but if the issue isn't replicated in a few days of testing we can close this and move on with our lives.

**Comment by vegasgeek** [comment]
I pulled the latest and I'm still seeing the same issue. If nothing has been pushed and I try clicking the lock first, nothing happens. But, if the Auto Update icon is already green, then the lock works fine.

FYI, nothing is showing up in the consol.

**Comment by allisonplus** [comment]
[ I'm seeing the same as John on my end with both click and keyboard navigation/selection. ]

**Comment by binarygary** [comment]
I guess during a merge a couple days back I accidentally nested the lock click event inside the update click event.

Fixed in: https://github.com/WebDevStudios/plugin-admin-notes/commit/c20b17a9982b7cce0d39486b1f1d3fcbda601b1a

**Comment by vegasgeek** [comment]
Woohoo! Fixed!
