### ISSUE TITLE
Icon a11y

### ISSUE THREAD

**Issue by allisonplus** [WebDevStudios/plugin-admin-notes#23]
Since the icons aren't purely for decoration and have interactive purpose, they need an aria-label to provide explain that purpose for those navigating by keyboard / using screen readers. Optional but perhaps recommend would also be adding a title attribute to add a tooltip.

(resource: http://fontawesome.io/accessibility/)

![screen shot 2017-01-26](https://cloud.githubusercontent.com/assets/10225971/22323383/8967e326-e370-11e6-9ffe-8f23451a0fbc.jpg)

**Comment by vegasgeek** [comment]
Great catch. We should definitely add tooltips that explain what the two icons do.

**Comment by binarygary** [comment]
Thanks @allisonplus 
I pushed a fix for the 2 icons: 
https://github.com/WebDevStudios/plugin-admin-notes/commit/504be2cc4d301b999f58eaf3fe867a2853e95298

**Comment by vegasgeek** [comment]
I added Title tags to the links as well.
