### ISSUE TITLE
Entire form loads as one admin-ajax request, should be split for each action

### ISSUE THREAD

**Issue by binarygary** [WebDevStudios/plugin-admin-notes#25]
Potentially a user could click auto-update and lock in rapid succession and the response from one request could arrive and provide misleading information causing a re-click on the incorrectly set icon. 

The solution is to update each individual component:
lock
auto-update
notes 
as 3 discreet request.

**Comment by binarygary** [comment]
Instead of breaking this into 3 requests I opted to replace the <div> with a "loading..." text on click of autoupdate/lock. 
This will prevent issues with lock/auto-update click in in rapid succession causing the first admin-ajax request to reply displaying the results of the first action, but not the second.

**Comment by vegasgeek** [comment]
I'm not really sure how to test this one myself. Is this something that maybe @tw2113 could test? or, honestly, if @binarygary is comfortable with it, I'm comfortable with it.

**Comment by binarygary** [comment]
it you click on autoupdate/lock "loading..." should display during the duration of the admin-ajax request.
