### ISSUE TITLE
i18n all text strings

### ISSUE THREAD

**Issue by vegasgeek** [WebDevStudios/plugin-admin-notes#26]
Update all text strings in the plugin to be i18n compatible so the plugin can be translated.

For example, the aria-label and title tags for the two icons, and the add note button text.

**Comment by binarygary** [comment]
I fixed this and submitted a PR. I have not done much i18n and would like to have it double-checked before merging into master.

https://github.com/WebDevStudios/plugin-admin-notes/pull/31
