### ISSUE TITLE
Focus state overlap

### ISSUE THREAD

**Issue by allisonplus** [WebDevStudios/plugin-admin-notes#30]
When input is focused, the emoji picker icon placement overlaps outline.

![screen shot 2017-01-28-focus-state](https://cloud.githubusercontent.com/assets/10225971/22397544/69d6b19a-e541-11e6-93b9-54eafe4dfb4f.jpg)

**Comment by allisonplus** [comment]
Ta-da!
![screen shot 2017-01-28-focus](https://cloud.githubusercontent.com/assets/10225971/22397596/d2325dc4-e542-11e6-9a34-5376c32392f6.jpg)

**Comment by binarygary** [comment]
@allisonplus you are 💣 .com!  That was bugging me and I didn't even realize it.
