### ISSUE TITLE
If a plugin is uninstalled and reinstalled the notes are preserved.

### ISSUE THREAD

**Issue by binarygary** [WebDevStudios/plugin-admin-notes#35]
Should we nuke the notes and settings?
Or is it okay to leave the notes and settings?

**Comment by tw2113** [comment]
I vote removing.

**Comment by binarygary** [comment]
I think that makes sense as well...working in a new branch on this.

**Comment by vegasgeek** [comment]
Can we define the definition of "uninstall" before we go with the nuclear option?

If, for example, I run into an issue where I need to turn off all plugins for a few minutes while I test something out, I don't want that to trigger the removal of all the data.

Can you let me know what would trigger the removal of the data?

**Comment by binarygary** [comment]
My definition was deleting the plugin.  
I think deactivated plugins could still benefit from a column of notes.

**Comment by vegasgeek** [comment]
OH!!!! I'm a bonehead. I was thinking you were talking about deleting ALL data that we had created if our plugin was uninstalled.

Yes, I would say that if our plugin is installed/active and another plugin is entirely removed from the plugin folder, this would be a good time to remove data associated with that plugin.

That being said, I would limit the check to happening no more than once per day so that it's not checking for all plugins' existence on every page load.

**Comment by tw2113** [comment]
In hindsight, it wasn't clear what plugin was being removed.

When our plugin is active, and a different plugin is removed, delete notes on it from our plugin.

When our plugin is deactivated and removed, delete ALL the notes. No footprints left behind

**Comment by vegasgeek** [comment]
@tw2113 that works for me.

**Comment by binarygary** [comment]
@vegasgeek I was thinking we wouldn't check daily but delete our notes when the plugin we are tracking is uninstalled.  There is a constant WP_UNINSTALL_PLUGIN when a plugin is being uninstalled that I think I can act on.

As far as removing the CPT and notes when we remove ours.  Agreed.
I'll get working on both of those.

**Comment by vegasgeek** [comment]
@binarygary Yep. sounds good!

**Comment by binarygary** [comment]
Please test the first part of this: 
https://github.com/WebDevStudios/plugin-admin-notes/pull/37

If a plugin is uninstalled the notes and settings are removed.

I'll work on how the plugin cleans up after itself tomorrow.
