### ISSUE TITLE
Invalid Argument supplied class-view.php on line 167

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/plugin-admin-notes#36]
![screen shot 2017-02-01 at 9 56 15 am](https://cloud.githubusercontent.com/assets/1626591/22519336/d2342f44-e864-11e6-8c93-1888110f842e.png)

Invalid argument supplied for foreach() in /plugins/plugin-admin-notes-master/includes/class-view.php on line 167

**Comment by binarygary** [comment]
Fixed, merged, and pushed.
