### ISSUE TITLE
Notes missing on non .org plugins.

### ISSUE THREAD

**Issue by KrashKartMedia** [WebDevStudios/plugin-admin-notes#8]
If you install a plugin, not on the .org repo, notes do not appear.  Adding a plugin from Github (https://github.com/bueltge/WordPress-Admin-Style) or (https://github.com/bradp/registered-post-types) notes do not show.

**Comment by binarygary** [comment]
This PR should fix this issue: https://github.com/WebDevStudios/Plugin-Notes/pull/9
Thanks for clearly defining what was causing the issue @KrashKartMedia 
It made the fix super quick.

Once that PR is merged we can close this issue.
